name: rare_disease_connect
description: A comprehensive platform for rare disease management and support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  csv: ^5.1.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/ 